/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAlumnos;
import Controlador.ControladorProfesor;
import Modelo.AlumnoProveedor;
import Modelo.ProfesorProveedor;
import Modelo.alumnos;
import Modelo.profesor;

/**
 *
 * @author Erika dlv
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegistrarAlumnos = new javax.swing.JButton();
        RegistrarProfesores = new javax.swing.JButton();
        jsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Academia TaeKwonDo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 11, 300, 30);

        RegistrarAlumnos.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        RegistrarAlumnos.setForeground(new java.awt.Color(255, 0, 0));
        RegistrarAlumnos.setText("Registro Alumnos");
        RegistrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarAlumnos);
        RegistrarAlumnos.setBounds(30, 70, 160, 29);

        RegistrarProfesores.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        RegistrarProfesores.setForeground(new java.awt.Color(255, 0, 0));
        RegistrarProfesores.setText("Registro Profesores");
        RegistrarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProfesoresActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarProfesores);
        RegistrarProfesores.setBounds(170, 120, 170, 30);

        jsalir.setFont(new java.awt.Font("Segoe UI Semilight", 3, 14)); // NOI18N
        jsalir.setForeground(new java.awt.Color(255, 51, 0));
        jsalir.setText("Salir");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jsalir);
        jsalir.setBounds(50, 170, 100, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/th.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 420, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAlumnosActionPerformed
                  
//        
    }//GEN-LAST:event_RegistrarAlumnosActionPerformed

    private void RegistrarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProfesoresActionPerformed
          
    }//GEN-LAST:event_RegistrarProfesoresActionPerformed

    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsalirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton RegistrarAlumnos;
    public javax.swing.JButton RegistrarProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jsalir;
    // End of variables declaration//GEN-END:variables
}
